version: 2.1
jobs:
  build:
   docker:
      - image: ubuntu:latest
   steps:
      - restore_cache:
          keys:
            - v1-apt-cache-{{ checksum "/var/lib/dpkg/available" }}
            - v1-apt-cache-
      - run:
          name: Setting up build environment
          command: |
           # APT cache
           rm /etc/apt/apt.conf.d/docker-clean
           echo "Binary::apt::APT::Keep-Downloaded-Packages \\"1\\";" >> /etc/apt/apt.conf.d/99keep-downloaded
           # Set up build environment
           apt-get update -y
           apt-get upgrade -y
           export DEBIAN_FRONTEND=noninteractive
           ln -fs /usr/share/zoneinfo/UTC /etc/localtime
           apt-get install tzdata -y
           dpkg-reconfigure --frontend noninteractive tzdata
           apt-get install bc bash git-core gnupg gnupg2 build-essential \
           zip curl make automake autogen autoconf autotools-dev libtool shtool python \
           m4 gcc libtool zlib1g-dev flex bison libssl-dev unzip tar xz-utils \
           software-properties-common device-tree-compiler wget ccache jq p7zip-full -y
           # Fix GitHub SSH key checking
           mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - save_cache:
          key: v1-apt-cache-{{ checksum "/var/lib/dpkg/available" }}
          paths:
            - /var/cache/apt
      - run: 
          name: Cloning kernel sources
          command: |
            git clone --depth 1 --single-branch --recurse-submodules "$CIRCLE_REPOSITORY_URL" --branch "$CIRCLE_BRANCH" .
      - restore_cache:
          keys:
            - v2-toolchains-clang-
      - run:
          name: Cloning toolchains
          command: |
           # too slow: git -C "proton-clang" pull --rebase || git clone https://github.com/kdrag0n/proton-clang.git --depth=1 --single-branch
           download_clang() {
              wget https://github.com/kdrag0n/proton-clang/archive/master.zip
              unzip -o master.zip
              echo $1 > proton-clang-master/last_proton   
           }
           clang_revision="$(curl https://api.github.com/repos/kdrag0n/proton-clang/commits/master | jq -r .sha)"
           if [ -d "proton-clang-master" ]; then 
            if [ ! "$clang_revision" == "$(cat proton-clang-master/last_proton)" ]; then
              download_clang $clang_revision
            fi
           else
            download_clang $clang_revision
           fi
      - save_cache:
          key: v2-toolchains-clang-{{ checksum "~/project/proton-clang-master/last_proton" }}
          paths:
            - ~/project/proton-clang-master
      - restore_cache:
          keys:
            - v2-compiler-cache-{{ .Branch }}-{{ .Revision }}
            - v2-compiler-cache-{{ .Branch }}-
            - v2-compiler-cache-
      - run:
          name: Starting build process
          command: |
           mkdir -p ~/project/ccache
           CCACHE_DIR=~/project/ccache ccache -M 500M
           mkdir -p /tmp/targets-output/
      - run:
          name: Building SDM439 target
          command: |
           export ARCH=arm64 && export SUBARCH=arm64 && export CCACHE_DIR=~/project/ccache
           make O=out ARCH=arm64 cherry-sdm439_defconfig
           export PATH="$(pwd)/proton-clang-master/bin:${PATH}"
           make -j$(nproc --all) O=out \
                                 ARCH=arm64 \
                                 CC="ccache clang" \
                                 CROSS_COMPILE=aarch64-linux-gnu- \
                                 CROSS_COMPILE_ARM32=arm-linux-gnueabi-
           aarch64-linux-gnu-strip --strip-unneeded --strip-debug out/drivers/staging/prima/wlan.ko
           out/scripts/sign-file sha512 out/certs/signing_key.pem out/certs/signing_key.x509 out/drivers/staging/prima/wlan.ko
           cp out/arch/arm64/boot/dtbo.img AnyKernel3/
           cp out/drivers/staging/prima/wlan.ko AnyKernel3/modules/vendor/lib/modules/pronto_wlan.ko
           cp out/drivers/staging/prima/wlan.ko AnyKernel3/modules/system/lib/modules/pronto_wlan.ko
           cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
      - save_cache:
          key: v2-compiler-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project/ccache
      - run:
          name: Creating flashable zip
          command: |
           mkdir -p /tmp/output
           cd AnyKernel3
           export zipfile="/tmp/output/CherryKernel_$(date +%Y%m%d-%H%M).zip"
           7z a -mm=Deflate -mfb=258 -mpass=15 -r $zipfile *
           FILE_CAPTION=$(cat \<< EOF
           *Branch:* ${CIRCLE_BRANCH}
           *Commit:* [$(echo $CIRCLE_SHA1 | cut -c -7)](https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/commit/${CIRCLE_SHA1})
           EOF
           )
           curl -F document=@"${zipfile}" -F "caption=${FILE_CAPTION}" "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument?chat_id=${TELEGRAM_CHAT_ID}&parse_mode=Markdown"
      - store_artifacts:
          path: /tmp/output
workflows:
  version: 2.1
  kernel:
    jobs:
      - build
